# Generated by Django 3.2 on 2021-04-29 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Roll', models.CharField(max_length=255)),
                ('Dob', models.DateField(default=django.utils.timezone.now)),
                ('Class', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('Created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
