# Generated by Django 3.2 on 2021-04-29 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Volume', models.CharField(max_length=255)),
                ('Update', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
