# Generated by Django 3.2 on 2021-04-29 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Membership_Date', models.DateField(default=django.utils.timezone.now)),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSApp.register')),
            ],
        ),
    ]
