# Generated by Django 3.2 on 2021-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
