# Generated by Django 3.2 on 2021-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0004_register_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_member',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
